# Nome do executável
PROG = programa

# Fontes
SRC = main.c TAD_LISTA/Lista.c

# Compilador
CC = gcc

# Flags de compilação
CFLAGS = -Wall -Wextra

# Regra principal
all:
	$(CC) $(CFLAGS) $(SRC) -o $(PROG)

# Limpa o executável
clean:
	rm -f $(PROG)
